export const MODAL_ACTION_CLOSE = "MODAL_ACTION_CLOSE";
export const MODAL_ACTION_CONFIRM = "MODAL_ACTION_CONFIRM";
export const MODAL_ACTION_SAVE_CHANGES = "MODAL_ACTION_SAVE_CHANGES";
export const MODAL_ACTION = "MODAL_ACTION";
